# Generated by Django 6.0.3 on 2026-04-03 10:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0003_maintenancerequest_photo"),
        ("wallet", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditBuilderLoan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "plan_months",
                    models.CharField(
                        choices=[("6", "6 Months"), ("12", "12 Months")],
                        default="12",
                        max_length=3,
                    ),
                ),
                (
                    "monthly_fee",
                    models.DecimalField(decimal_places=2, default=1500.0, max_digits=8),
                ),
                (
                    "monthly_principal",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("monthly_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_fees", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "total_repayable",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "score_at_start",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "score_current",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("defaulted", "Defaulted"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_builder_loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vault_pocket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_builder_loan",
                        to="wallet.savingspocket",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_builder_loans",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CreditBuilderRepayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("instalment_number", models.PositiveSmallIntegerField()),
                (
                    "principal_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("fee_amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("monthly_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("due_date", models.DateField()),
                ("paid_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("paid", "Paid"),
                            ("missed", "Missed"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("reported_to_bureau", models.BooleanField(default=False)),
                ("bureau_reference", models.CharField(blank=True, max_length=128)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repayments",
                        to="financing.creditbuilderloan",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wallet.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["instalment_number"],
            },
        ),
        migrations.CreateModel(
            name="RentAdvance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount_requested",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "amount_approved",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "repayment_months",
                    models.CharField(
                        choices=[
                            ("3", "3 Months"),
                            ("6", "6 Months"),
                            ("9", "9 Months"),
                        ],
                        default="6",
                        max_length=2,
                    ),
                ),
                (
                    "flat_fee_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "flat_fee_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "total_repayable",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "monthly_repayment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("defaulted", "Defaulted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reported_to_bureau", models.BooleanField(default=False)),
                ("disbursed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advances",
                        to="tenancy.lease",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rent_advances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rent_advances",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RentAdvanceRepayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("due_date", models.DateField()),
                ("paid_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("paid", "Paid"),
                            ("missed", "Missed"),
                            ("waived", "Waived"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("reported_to_bureau", models.BooleanField(default=False)),
                ("instalment_number", models.PositiveSmallIntegerField()),
                (
                    "advance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repayments",
                        to="financing.rentadvance",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wallet.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["instalment_number"],
            },
        ),
        migrations.CreateModel(
            name="UtilityAdvance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "utility_type",
                    models.CharField(
                        choices=[
                            ("electricity", "Electricity"),
                            ("gas", "Gas"),
                            ("water", "Water"),
                            ("internet", "Internet"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider_name", models.CharField(max_length=64)),
                ("account_number", models.CharField(blank=True, max_length=50)),
                (
                    "amount_requested",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "flat_fee_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "flat_fee_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_repayable",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "repayment_months",
                    models.CharField(
                        choices=[
                            ("1", "1 Month"),
                            ("2", "2 Months"),
                            ("3", "3 Months"),
                        ],
                        default="2",
                        max_length=2,
                    ),
                ),
                (
                    "monthly_repayment",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("defaulted", "Defaulted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("disbursed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utility_advances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utility_advances",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UtilityAdvanceRepayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("due_date", models.DateField()),
                ("paid_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("paid", "Paid"),
                            ("missed", "Missed"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("instalment_number", models.PositiveSmallIntegerField()),
                ("reported_to_bureau", models.BooleanField(default=False)),
                (
                    "advance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repayments",
                        to="financing.utilityadvance",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wallet.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["instalment_number"],
            },
        ),
    ]
