# Generated by Django 6.0.3 on 2026-03-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_bvn_user_bvn_verified_user_nin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address_line1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="address_line2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="employer_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="kyc_tier",
            field=models.IntegerField(
                choices=[
                    (0, "Unverified"),
                    (1, "Basic"),
                    (2, "Financial"),
                    (3, "Financing"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="lga",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="monthly_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="nok_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="nok_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="nok_relationship",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
