# Generated by Django 6.0.3 on 2026-03-23 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_address_line1_user_address_line2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pin_hash",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="user",
            name="pin_set",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_completion",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
        migrations.AddField(
            model_name="user",
            name="referral_code",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="user",
            name="referral_path",
            field=models.TextField(
                blank=True,
                help_text="Pipe-separated chain of ancestor user IDs. e.g. 1|4|7",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_referrals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="DeviceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_token", models.CharField(max_length=128, unique=True)),
                ("device_name", models.CharField(blank=True, max_length=128)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("web", "Web"),
                        ],
                        default="android",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_used", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_used"],
            },
        ),
        migrations.CreateModel(
            name="ReferralCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credit_type",
                    models.CharField(
                        choices=[
                            ("signup", "New User Signup"),
                            ("kyc", "Referral Completed KYC"),
                            ("payment", "Referral Made First Payment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        help_text="1 = direct referral, 2 = referral of referral, etc."
                    ),
                ),
                ("points", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_credits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_events_generated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("employed", "Employed"),
                            ("self_employed", "Self Employed"),
                            ("student", "Student"),
                            ("unemployed", "Unemployed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("job_title", models.CharField(blank=True, max_length=128)),
                ("emergency_name", models.CharField(blank=True, max_length=128)),
                ("emergency_phone", models.CharField(blank=True, max_length=20)),
                ("emergency_relation", models.CharField(blank=True, max_length=64)),
                ("referee1_name", models.CharField(blank=True, max_length=128)),
                ("referee1_phone", models.CharField(blank=True, max_length=20)),
                ("referee1_relation", models.CharField(blank=True, max_length=64)),
                ("referee2_name", models.CharField(blank=True, max_length=128)),
                ("referee2_phone", models.CharField(blank=True, max_length=20)),
                ("referee2_relation", models.CharField(blank=True, max_length=64)),
                ("bio", models.TextField(blank=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
