# Generated by Django 6.0.3 on 2026-03-23 22:39

import random
import string
from django.db import migrations, models


def populate_referral_codes(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    for user in User.objects.filter(referral_code__in=[None, '']).iterator():
        while True:
            code = 'KH' + ''.join(
                random.choices(
                    string.ascii_uppercase + string.digits, k=8
                )
            )
            if not User.objects.filter(referral_code=code).exists():
                user.referral_code = code
                user.save(update_fields=['referral_code'])
                break


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20260323_2239"),
    ]

    operations = [
        migrations.RunPython(populate_referral_codes),
        migrations.AlterField(
            model_name="user",
            name="referral_code",
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
