# Generated by Django 6.0.3 on 2026-03-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="units/"),
        ),
    ]
