# Generated by Django 6.0.3 on 2026-03-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0002_unit_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancerequest",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="maintenance/"),
        ),
    ]
