# Generated by Django 6.0.3 on 2026-03-26 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
        ("tenancy", "0003_maintenancerequest_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="tenancy.property",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="lease",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="tenancy.lease",
            ),
        ),
    ]
