# Generated by Django 6.0.3 on 2026-03-26 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_conversation_property_alter_conversation_lease"),
        ("utilities", "0004_supplier_supplieravailability_supplierservice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="supplier_service_request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversation",
                to="utilities.supplierservicerequest",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="context_type",
            field=models.CharField(
                choices=[
                    ("landlord", "Landlord"),
                    ("homeowner", "Homeowner"),
                    ("vendor", "Vendor"),
                    ("neighbor", "Neighbor"),
                    ("supplier", "Supplier"),
                ],
                max_length=20,
            ),
        ),
    ]
