# Generated by Django 6.0.3 on 2026-04-03 10:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavingsPocket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pocket_type",
                    models.CharField(
                        choices=[
                            ("rent", "Next Rent"),
                            ("home_deposit", "Home Deposit"),
                            ("emergency", "Emergency Fund"),
                            ("credit_vault", "Credit Builder Vault"),
                            ("utility", "Utility Fund"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Savings goal amount",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Locked pockets cannot be withdrawn from manually",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("NGN", "Nigerian Naira"), ("USD", "US Dollar")],
                        default="NGN",
                        max_length=3,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
                ),
                (
                    "ledger_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Balance including pending transactions",
                        max_digits=14,
                    ),
                ),
                ("virtual_account_number", models.CharField(blank=True, max_length=20)),
                ("virtual_bank_name", models.CharField(blank=True, max_length=64)),
                ("flutterwave_ref", models.CharField(blank=True, max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "currency")},
            },
        ),
        migrations.CreateModel(
            name="VirtualAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=20)),
                ("bank_name", models.CharField(max_length=64)),
                ("account_name", models.CharField(max_length=128)),
                ("flutterwave_ref", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="virtual_account",
                        to="wallet.wallet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("credit", "Credit"),
                            ("debit", "Debit"),
                            ("transfer_in", "Transfer In"),
                            ("transfer_out", "Transfer Out"),
                            ("rent_payment", "Rent Payment"),
                            ("utility_payment", "Utility Payment"),
                            ("advance_credit", "Advance Disbursement"),
                            ("advance_repay", "Advance Repayment"),
                            ("savings_deposit", "Savings Deposit"),
                            ("savings_withdraw", "Savings Withdrawal"),
                            ("fee", "Platform Fee"),
                            ("refund", "Refund"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="NGN", max_length=3)),
                (
                    "balance_before",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("reversed", "Reversed"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True)),
                ("provider_ref", models.CharField(blank=True, max_length=128)),
                ("provider", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "related_pocket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wallet.savingspocket",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="savingspocket",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pockets",
                to="wallet.wallet",
            ),
        ),
    ]
