# Generated by Django 6.0.3 on 2026-04-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savingspocket",
            name="is_locked",
            field=models.BooleanField(
                default=True,
                help_text="Locked pockets cannot be withdrawn from manually",
            ),
        ),
        migrations.AlterField(
            model_name="savingspocket",
            name="pocket_type",
            field=models.CharField(
                choices=[
                    ("rent", "Next Rent"),
                    ("home_deposit", "Home Deposit"),
                    ("emergency", "Emergency Fund"),
                    ("credit_vault", "Credit Builder Vault"),
                    ("utility", "Utility Fund"),
                    ("groceries", "Groceries"),
                    ("vacation", "Vacation Fund"),
                    ("education", "Education Fund"),
                    ("custom", "Custom"),
                ],
                default="custom",
                max_length=20,
            ),
        ),
    ]
