# Generated by Django 6.0.3 on 2026-04-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_alter_savingspocket_is_locked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="savingspocket",
            name="locked_at",
            field=models.DateTimeField(
                blank=True, help_text="When the pocket was locked", null=True
            ),
        ),
        migrations.AddField(
            model_name="savingspocket",
            name="unlock_available_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the pocket becomes unlockable (3 days after request)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="savingspocket",
            name="unlock_requested_at",
            field=models.DateTimeField(
                blank=True, help_text="When the user requested an unlock", null=True
            ),
        ),
    ]
