# Generated by Django 6.0.3 on 2026-03-26 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utilities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UtilityMeterProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("smart_meter", "Smart Meter (Auto Push)"),
                            ("manual_reading", "Manual Meter Reading"),
                            ("hybrid", "Hybrid (Smart + Manual Override)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "reading_type",
                    models.CharField(
                        choices=[
                            ("consumption", "Direct Consumption (kWh, L)"),
                            ("meter_difference", "Previous vs Current Reading"),
                        ],
                        default="meter_difference",
                        max_length=50,
                    ),
                ),
                (
                    "provider_name",
                    models.CharField(
                        blank=True,
                        help_text="e.g., EEDC, Lagos Water, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="API key for smart meter provider (should be encrypted)",
                        max_length=500,
                    ),
                ),
                (
                    "webhook_token",
                    models.CharField(
                        blank=True,
                        help_text="Token to validate webhook requests",
                        max_length=255,
                    ),
                ),
                (
                    "manual_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_reading_date", models.DateField(blank=True, null=True)),
                ("last_sync_attempt", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meter_provider",
                        to="utilities.utilityaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meter Provider",
            },
        ),
        migrations.CreateModel(
            name="UtilityMeterReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_reading",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Reading from last period",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "current_reading",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Reading for this period",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "consumption",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Direct consumption (kWh, litres, etc)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("reading_date", models.DateField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("smart_meter", "Smart Meter (API Push)"),
                            ("manual", "Manual Tenant Input"),
                            ("import", "Bulk Import"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_processed", models.BooleanField(default=False)),
                ("is_confirmed", models.BooleanField(default=False)),
                (
                    "submitted_by",
                    models.CharField(
                        blank=True,
                        help_text="Tenant name or API system",
                        max_length=255,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meter_readings",
                        to="utilities.utilityaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-reading_date"],
                "unique_together": {("account", "reading_date")},
            },
        ),
        migrations.CreateModel(
            name="UtilityRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kwh", "Kilowatt Hours"),
                            ("liters", "Litres"),
                            ("mbps", "Megabits per Second"),
                            ("units", "Units"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Cost per unit (e.g., ₦50 per kWh)",
                        max_digits=10,
                    ),
                ),
                (
                    "fixed_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monthly fixed charge",
                        max_digits=10,
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "utility",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate",
                        to="utilities.utility",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Utility Rates",
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="UtilityUsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consumption", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kwh", "Kilowatt Hours"),
                            ("liters", "Litres"),
                            ("mbps", "Megabits per Second"),
                            ("units", "Units"),
                        ],
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("unit_rate", models.DecimalField(decimal_places=4, max_digits=10)),
                ("variable_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "fixed_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_billed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="utilities.utilityaccount",
                    ),
                ),
                (
                    "meter_reading",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_record",
                        to="utilities.utilitymeterreading",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_end"],
            },
        ),
    ]
