# Generated by Django 6.0.3 on 2026-03-26 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "utilities",
            "0002_utilitymeterprovider_utilitymeterreading_utilityrate_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="utilityrate",
            options={
                "ordering": ["utility", "band", "-effective_from"],
                "verbose_name_plural": "Utility Rates",
            },
        ),
        migrations.AddField(
            model_name="utilitymeterprovider",
            name="tariff_band",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "Band A"),
                    ("B", "Band B"),
                    ("C", "Band C"),
                    ("D", "Band D"),
                    ("E", "Band E"),
                ],
                help_text="Tariff band (A-E) selected for this account",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="utilitymeterreading",
            name="tariff_band",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "Band A"),
                    ("B", "Band B"),
                    ("C", "Band C"),
                    ("D", "Band D"),
                    ("E", "Band E"),
                ],
                help_text="Optional selected tariff band for this reading",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="utilityrate",
            name="band",
            field=models.CharField(
                choices=[
                    ("A", "Band A"),
                    ("B", "Band B"),
                    ("C", "Band C"),
                    ("D", "Band D"),
                    ("E", "Band E"),
                ],
                default="C",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="utilityrate",
            name="max_consumption",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Highest consumption value for wage band (optional)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="utilityrate",
            name="min_consumption",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Lowest consumption value for wage band (optional)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="utilityrate",
            name="fixed_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Fixed charge for this band",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="utilityrate",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kwh", "Kilowatt Hours"),
                    ("liters", "Litres"),
                    ("mbps", "Megabits per Second"),
                    ("units", "Units"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="utilityrate",
            name="utility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates",
                to="utilities.utility",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="utilityrate",
            unique_together={("utility", "band", "effective_from")},
        ),
    ]
