# Generated by Django 6.0.3 on 2026-03-27 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utilities", "0004_supplier_supplieravailability_supplierservice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suppliermessage",
            name="sender_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.CreateModel(
            name="WaterSupplierDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "water_type",
                    models.CharField(
                        choices=[
                            ("sachet", "Sachet Water"),
                            ("tanker", "Tanker Delivery"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "sachets_per_bag",
                    models.IntegerField(
                        default=50, help_text="Number of sachets per bag (usually 50)"
                    ),
                ),
                (
                    "ml_per_sachet",
                    models.IntegerField(
                        default=500, help_text="Volume per sachet in ml (usually 500ml)"
                    ),
                ),
                (
                    "min_order_bags",
                    models.IntegerField(default=2, help_text="Minimum bags per order"),
                ),
                (
                    "nafdac_certified",
                    models.BooleanField(
                        default=False, help_text="NAFDAC approval for sachet water"
                    ),
                ),
                (
                    "volume_options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='e.g. [{"litres": 5000, "price": 15000}, {"litres": 10000, "price": 25000}]',
                    ),
                ),
                (
                    "free_delivery_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Order value above which delivery is free",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "supplier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="water_detail",
                        to="utilities.supplier",
                    ),
                ),
            ],
        ),
    ]
