"""
Django settings for kredhaus project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Configuration
SECRET_KEY = config('SECRET_KEY')
DEBUG      = config('DEBUG', cast=bool, default=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-=sb+m!aki3pe88tg6&b6o*cs&mx^30gr*57q7)*5ozeii9u0jv"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third party
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist', #blacklisting the refresh token — once blacklisted it can never be used again to generate new access tokens.

    # Kredhaus apps
    'accounts',
    'tenancy',
    'messaging', # for real-time chat between tenants and landlords
    'utilities',
    'channels',  # for WebSocket support 
    'wallet',    # for balances, transactions, savings pockets, virtual accounts
    'financing', # for loan applications and financial services such as Rent Advance, Utility Advance, Credit Builder Loan etc
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "kredhaus.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "kredhaus.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME':  timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES':      ('Bearer',),
}

# Channels configuration for WebSocket support (real-time chat)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [("127.0.0.1", 6379)]},
    }
}

# For local dev without Redis, use in-memory (single server only):
# "BACKEND": "channels.layers.InMemoryChannelLayer"
# =========================================================


# REF
# This references the KYC permission for each user that enables them to perform various actions on the app
# based on the information that they provide and we collect.
# If the user does not meet the tier requirement they get a clear error message back
KYC_TIER_PERMISSIONS = {
    0: [
        'Browse property listings',
        'View public profiles',
    ],
    1: [
        'Submit maintenance requests',
        'View credit score',
        'Basic payments',
        'Send messages',
    ],
    2: [
        'Pay rent',
        'Access savings pockets',
        'Credit building reporting',
        'Sign leases',
    ],
    3: [
        'Rent-to-own scheme',
        'BNPL rent advance',
        'Premium financing products',
        'Mortgage referrals',
    ],
}


# ── Flutterwave ────────────────────────────────────────────────────────────
# Flutterwave is our payment processor, used for all payments and disbursements on the platform. 
# We use their API to create payment links, process payments, manage virtual accounts, and handle payouts to landlords and suppliers.
FLUTTERWAVE_SECRET_KEY  = config('FLUTTERWAVE_SECRET_KEY', default='')
FLUTTERWAVE_PUBLIC_KEY  = config('FLUTTERWAVE_PUBLIC_KEY', default='')
FLUTTERWAVE_BASE_URL    = 'https://api.flutterwave.com/v3'
FLUTTERWAVE_WEBHOOK_SECRET = config('FLUTTERWAVE_WEBHOOK_SECRET', default='')

# ── Wallet ─────────────────────────────────────────────────────────────────
# The wallet system tracks user balances, transactions, and virtual accounts. 
# It integrates with Flutterwave for funding and payouts, and supports multiple currencies.
WALLET_CURRENCIES       = ['NGN', 'USD']
WALLET_DEFAULT_CURRENCY = 'NGN'
PLATFORM_FEE_PERCENT    = 1.5    # 1.5% on transactions

# ── Financing ──────────────────────────────────────────────────────────────
# This section defines the parameters for our financing products, including Rent Advance, Utility Advance, and Credit Builder Loans.
RENT_ADVANCE_MAX_PERCENT  = 50    # max 50% of rent cycle
RENT_ADVANCE_FEES         = {'3': 3.0, '6': 5.0, '9': 7.0}
UTILITY_ADVANCE_MAX       = 50000 # ₦50,000
UTILITY_ADVANCE_FEES      = {'1': 2.0, '2': 3.5, '3': 5.0}
CREDIT_BUILDER_MONTHLY_FEE = 1500 # ₦1,500/month